import './globals.css';
import localFont from 'next/font/local';
import Navbar from './components/nav/Nav';
import Footer from './components/Footer';

// const unileverShillingFonts = localFont({
//   src: [
//     {
//       src: '../public/fonts/UnileverShillingBold.ttf',
//       variable: 'fontsBold',
//     },
//     {
//       src: '../public/fonts/UnileverShilling.ttf',
//       variable: 'font',
//     },
//   ],
//   variable: '--font-unilever',
// });

export const metadata = {
  title: 'Hap App',
  description: 'Generated by Hap',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
